# Generated by Django 2.1.4 on 2019-01-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taboocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taboocard',
            name='answered_correctly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taboocard',
            name='times_shown',
            field=models.IntegerField(default=0),
        ),
    ]
