# Generated by Django 2.1.4 on 2018-12-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181214_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='external_source',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
