# Generated by Django 2.1.4 on 2018-12-15 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(related_name='selected_languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
