# Generated by Django 2.1.4 on 2019-01-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181216_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
