# Generated by Django 2.1.4 on 2019-01-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190105_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.CharField(choices=[('1', 'Bronze'), ('2', 'Silver'), ('3', 'Gold'), ('4', 'Diamond')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition',
            field=models.TextField(max_length=2048),
        ),
    ]
