# Generated by Django 2.1.4 on 2019-01-06 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190106_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
